require: rubocop-rspec

AllCops:
  DisplayCopNames: true
  Exclude:
    - "*.gemspec"
    - "bin/*"
Style/FrozenStringLiteralComment:
  Description: >-
    Add the frozen_string_literal comment to the top of files
    to help transition from Ruby 2.3.0 to Ruby 3.0.
  Enabled: false
Style/StringLiterals:
  Description: Checks if uses of quotes match the configured preference.
  StyleGuide: https://github.com/bbatsov/ruby-style-guide#consistent-string-literals
  Enabled: true
  EnforcedStyle: double_quotes
  SupportedStyles:
  - single_quotes
  - double_quotes
Style/Documentation:
  Description: Document classes and non-namespace modules.
  Enabled: false
